QUESTIONS = {
    "algebra": {
        "easy": [
            {"question": r"Simplify: \(2x + 5x\)", "answer": r"7x"},
            {"question": r"Simplify: \(3a - a\)", "answer": r"2a"},
            {"question": r"Expand: \(2(x+3)\)", "answer": r"2x + 6"},
            {"question": r"Simplify: \(4y - 9 + y\)", "answer": r"5y - 9"},
            {"question": r"Expand: \(3(x - 2)\)", "answer": r"3x - 6"},
            {"question": r"Simplify: \(5m + 2m - m\)", "answer": r"6m"},
            {"question": r"Simplify: \(9k - 4k\)", "answer": r"5k"},
            {"question": r"Expand: \(6(2 - x)\)", "answer": r"12 - 6x"},
            {"question": r"Simplify: \(3(x + 4) - x\)", "answer": r"2x + 12"},
            {"question": r"Factor: \(x^2 + 5x\)", "answer": r"x(x+5)"},
            {"question": r"Simplify: \(2(a+b)\)", "answer": r"2a + 2b"},
            {"question": r"Expand: \((x+2)(x+3)\)", "answer": r"x^2 + 5x + 6"},
            {"question": r"Simplify: \(a^2 \cdot a^3\)", "answer": r"a^5"},
            {"question": r"Simplify: \(\frac{x^3}{x}\)", "answer": r"x^2"},
            {"question": r"Simplify: \(4(x-1) + 2\)", "answer": r"4x - 2"},
            {"question": r"Factor: \(x^2 - 9\)", "answer": r"(x-3)(x+3)"},
            {"question": r"Expand: \(2x(x+1)\)", "answer": r"2x^2 + 2x"},
            {"question": r"Simplify: \(\frac{3x}{6}\)", "answer": r"\frac{x}{2}"},
            {"question": r"Simplify: \(7y^2 + 2y^2\)", "answer": r"9y^2"},
            {"question": r"Simplify: \(10 - (3x - 2)\)", "answer": r"12 - 3x"},
            {"question": r"Simplify: \(2(x-3) + 3(x+2)\)", "answer": r"5x"},
            {"question": r"Factor: \(x^2 + 8x + 15\)", "answer": r"(x+3)(x+5)"}
        ],
        "hard": [
            {"question": r"Factor: \(2x^2 - 8x\)", "answer": r"2x(x-4)"},
            {"question": r"Simplify: \(\frac{4x^2 - 9}{2x - 3}\)", "answer": r"2x + 3"},
            {"question": r"Expand: \((2x-3)(x+4)\)", "answer": r"2x^2 + 5x - 12"},
            {"question": r"Simplify: \(\frac{x^3 - 27}{x - 3}\)", "answer": r"x^2 + 3x + 9"},
            {"question": r"Factor: \(x^3 + x^2 - 6x\)", "answer": r"x(x+3)(x-2)"},
            {"question": r"Simplify: \(\frac{3x}{x^2 - 9}\)", "answer": r"\frac{3x}{(x-3)(x+3)}"},
            {"question": r"Expand: \((x-5)^3\)", "answer": r"x^3 - 15x^2 + 75x - 125"},
            {"question": r"Factor completely: \(4x^2 - 25\)", "answer": r"(2x-5)(2x+5)"},
            {"question": r"Simplify: \(\frac{x^4}{x^{-2}}\)", "answer": r"x^6"},
            {"question": r"Expand: \((3x - 2)(3x + 2)\)", "answer": r"9x^2 - 4"},
            {"question": r"Simplify: \(2(x^2 - 3x + 1) - (x^2 - 4x)\)", "answer": r"x^2 - 2x + 2"},
            {"question": r"Factor: \(3x^2 - 11x - 4\)", "answer": r"(3x+1)(x-4)"},
            {"question": r"Expand: \((x + 2)(x^2 - 2x + 4)\)", "answer": r"x^3 + 8"},
            {"question": r"Simplify: \(\frac{6x^2y}{3xy^2}\)", "answer": r"\frac{2x}{y}"},
            {"question": r"Factor: \(x^4 - 16\)", "answer": r"(x^2-4)(x^2+4)"},
            {"question": r"Simplify: \(\frac{x^2 - 4x + 4}{x-2}\)", "answer": r"x - 2"},
            {"question": r"Expand: \((2x - 3)^3\)", "answer": r"8x^3 - 36x^2 + 54x - 27"},
            {"question": r"Simplify: \(3x - 2(4 - x)\)", "answer": r"5x - 8"},
            {"question": r"Factor: \(2x^2 + 7x + 3\)", "answer": r"(2x+1)(x+3)"},
            {"question": r"Simplify: \(\frac{x^3y^2}{xy}\)", "answer": r"x^2 y"},
            {"question": r"Factor completely: \(x^3 - x\)", "answer": r"x(x-1)(x+1)"}
        ]
    },

    "equations": {
        "easy": [
            {"question": r"Solve: \(2x = 10\)", "answer": r"x = 5"},
            {"question": r"Solve: \(x + 7 = 12\)", "answer": r"x = 5"},
            {"question": r"Solve: \(3x - 6 = 0\)", "answer": r"x = 2"},
            {"question": r"Solve: \(4x + 1 = 9\)", "answer": r"x = 2"},
            {"question": r"Solve: \(5x = 20\)", "answer": r"x = 4"},
            {"question": r"Solve: \(x - 9 = 3\)", "answer": r"x = 12"},
            {"question": r"Solve: \(7x + 7 = 0\)", "answer": r"x = -1"},
            {"question": r"Solve: \(9 = 3x\)", "answer": r"x = 3"},
            {"question": r"Solve: \(2(x-3)=4\)", "answer": r"x = 5"},
            {"question": r"Solve: \(3x + 2x = 10\)", "answer": r"x = 2"},
            {"question": r"Solve: \(x + \frac{1}{2} = 1\)", "answer": r"x = \frac{1}{2}"},
            {"question": r"Solve: \(\frac{x}{3} = 2\)", "answer": r"x = 6"},
            {"question": r"Solve: \(5 - x = 1\)", "answer": r"x = 4"},
            {"question": r"Solve: \(4 - 2x = 0\)", "answer": r"x = 2"},
            {"question": r"Solve: \(3(x+1)=12\)", "answer": r"x = 3"},
            {"question": r"Solve: \(\frac{x-2}{4}=3\)", "answer": r"x = 14"},
            {"question": r"Solve: \(x^2 = 16\)", "answer": r"x = \pm 4"},
            {"question": r"Solve: \(|x|=7\)", "answer": r"x = \pm7"},
            {"question": r"Solve: \(x^2 - 9 = 0\)", "answer": r"x = \pm 3"},
            {"question": r"Solve: \(2x + 3 = 3x\)", "answer": r"x = 3"},
            {"question": r"Solve: \(6x - 4 = 2x\)", "answer": r"x = 1"}
        ],
        "hard": [
            {"question": r"Solve: \(3x - 2 = x + 4\)", "answer": r"x = 3"},
            {"question": r"Solve: \(2(x-4) = 3(x+2)\)", "answer": r"x = -16"},
            {"question": r"Solve: \(\frac{x+3}{2} = \frac{x-5}{3}\)", "answer": r"x = -19"},
            {"question": r"Solve: \(4x - 7 = 2(3x+1)\)", "answer": r"x = -9"},
            {"question": r"Solve: \(x^2 - 5x + 6=0\)", "answer": r"x = 2,\; 3"},
            {"question": r"Solve: \(2x^2 - 8x = 0\)", "answer": r"x = 0,\; 4"},
            {"question": r"Solve: \(x^2 = 5x\)", "answer": r"x = 0,\; 5"},
            {"question": r"Solve: \(3x^2 + 2x - 1 = 0\)", "answer": r"x = \frac{-2 \pm 4}{6}"},
            {"question": r"Solve: \(\frac{2}{x} = 4\)", "answer": r"x = \frac{1}{2}"},
            {"question": r"Solve: \(x + \frac{3}{x} = 4\)", "answer": r"x = 1,\; 3"},
            {"question": r"Solve: \(x^2 - 2x - 8 = 0\)", "answer": r"x = 4,\; -2"},
            {"question": r"Solve: \(4^{x} = 16\)", "answer": r"x = 2"},
            {"question": r"Solve: \(3^{x} = 27\)", "answer": r"x = 3"},
            {"question": r"Solve: \(e^{x} = 5\)", "answer": r"x = \ln 5"},
            {"question": r"Solve: \(\ln(x) = 2\)", "answer": r"x = e^{2}"},
            {"question": r"Solve: \(x^2 + x - 12 = 0\)", "answer": r"x = 3,\; -4"},
            {"question": r"Solve: \(\sqrt{x+4}=5\)", "answer": r"x = 21"},
            {"question": r"Solve: \(3^x = 9\)", "answer": r"x = 2"},
            {"question": r"Solve: \(\frac{x-1}{x+1}=2\)", "answer": r"x = -3"},
            {"question": r"Solve: \(x^3 = 27\)", "answer": r"x = 3"},
            {"question": r"Solve: \(x^2 + 2x = 15\)", "answer": r"x = 3,\; -5"}
        ]
    },

    "calculus": {
        "easy": [
            {"question": r"Differentiate: \(f(x)=x^2\)", "answer": r"f'(x)=2x"},
            {"question": r"Differentiate: \(f(x)=3x\)", "answer": r"f'(x)=3"},
            {"question": r"Differentiate: \(f(x)=x^3\)", "answer": r"f'(x)=3x^2"},
            {"question": r"Differentiate: \(f(x)=5\)", "answer": r"f'(x)=0"},
            {"question": r"Differentiate: \(f(x)=2x^2+3x\)", "answer": r"f'(x)=4x+3"},
            {"question": r"Differentiate: \(f(x)=\sqrt{x}\)", "answer": r"f'(x)=\frac{1}{2\sqrt{x}}"},
            {"question": r"Differentiate: \(f(x)=\frac{1}{x}\)", "answer": r"f'(x)=-\frac{1}{x^2}"},
            {"question": r"Differentiate: \(f(x)=x^4\)", "answer": r"f'(x)=4x^3"},
            {"question": r"Differentiate: \(f(x)=7x^3\)", "answer": r"f'(x)=21x^2"},
            {"question": r"Differentiate: \(f(x)=2x+9\)", "answer": r"f'(x)=2"},
            {"question": r"Differentiate: \(f(x)=\ln x\)", "answer": r"f'(x)=\frac{1}{x}"},
            {"question": r"Differentiate: \(f(x)=e^x\)", "answer": r"f'(x)=e^x"},
            {"question": r"Differentiate: \(f(x)=\sin x\)", "answer": r"f'(x)=\cos x"},
            {"question": r"Differentiate: \(f(x)=\cos x\)", "answer": r"f'(x)=-\sin x"},
            {"question": r"Differentiate: \(f(x)=x^2+5\)", "answer": r"2x"},
            {"question": r"Differentiate: \(f(x)=4x^2 - 3x\)", "answer": r"8x - 3"},
            {"question": r"Differentiate: \(f(x)=x^{-2}\)", "answer": r"f'(x)=-2x^{-3}"},
            {"question": r"Differentiate: \(f(x)=3x^{1/2}\)", "answer": r"f'(x)=\frac{3}{2\sqrt{x}}"},
            {"question": r"Differentiate: \(f(x)=x^5\)", "answer": r"f'(x)=5x^4"},
            {"question": r"Differentiate: \(f(x)=\tan x\)", "answer": r"f'(x)=\sec^2 x"}
        ],
        "hard": [
            {"question": r"Differentiate: \(f(x)=\frac{x^2+3}{x}\)", "answer": r"1 - \frac{3}{x^2}"},
            {"question": r"Differentiate: \(f(x)=x^2 e^x\)", "answer": r"e^x(x^2 + 2x)"},
            {"question": r"Differentiate: \(f(x)=\ln(x^2+1)\)", "answer": r"\frac{2x}{x^2+1}"},
            {"question": r"Differentiate: \(f(x)=\frac{3x+1}{x^2}\)", "answer": r"-\frac{3}{x^2} - \frac{2}{x^3}"},
            {"question": r"Differentiate: \(f(x)=e^{3x}\)", "answer": r"3e^{3x}"},
            {"question": r"Differentiate: \(f(x)=\sin(2x)\)", "answer": r"2\cos(2x)"},
            {"question": r"Differentiate: \(f(x)=\cos(3x)\)", "answer": r"-3\sin(3x)"},
            {"question": r"Differentiate: \(f(x)=x^3\ln x\)", "answer": r"x^2(3\ln x + 1)"},
            {"question": r"Differentiate: \(f(x)=\sqrt{x^2+4}\)", "answer": r"\frac{x}{\sqrt{x^2+4}}"},
            {"question": r"Differentiate: \(f(x)=\frac{1}{x^3}\)", "answer": r"-3x^{-4}"},
            {"question": r"Differentiate: \(f(x)=\tan(4x)\)", "answer": r"4\sec^2(4x)"},
            {"question": r"Differentiate: \(f(x)=x e^x\)", "answer": r"e^x(x + 1)"},
            {"question": r"Differentiate: \(f(x)=\ln(\sin x)\)", "answer": r"\cot x"},
            {"question": r"Differentiate: \(f(x)=\ln(\cos x)\)", "answer": r"-\tan x"},
            {"question": r"Differentiate: \(f(x)=x^x\)", "answer": r"x^x(\ln x + 1)"},
            {"question": r"Differentiate: \(f(x)=\frac{2x}{x+1}\)", "answer": r"\frac{2}{(x+1)^2}"},
            {"question": r"Differentiate: \(f(x)=\arctan x\)", "answer": r"\frac{1}{1+x^2}"},
            {"question": r"Differentiate: \(f(x)=x^2\sin x\)", "answer": r"2x\sin x + x^2\cos x"},
            {"question": r"Differentiate: \(f(x)=\frac{x}{\ln x}\)", "answer": r"\frac{\ln x - 1}{(\ln x)^2}"},
            {"question": r"Differentiate: \(f(x)=e^{-x^2}\)", "answer": r"-2x e^{-x^2}"}
        ]
    }
}
